# Generated by Django 2.0.4 on 2019-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name1', models.CharField(max_length=30)),
                ('catalog_name2', models.CharField(max_length=30)),
                ('catalog_name3', models.CharField(max_length=30)),
            ],
        ),
    ]
